if #arg ~= 2  then 
	print("rawprint: usage  rawprint.lua <analysis-file> <field>")
	return -1
end


print("# Autogenerated by Trisul jacktheribber at "..os.date())

local res=require(arg[1]) 
for k,v in pairs(res[arg[2]]) do
	print(k)
end    
